const express = require('express');
const { authenticate, authorize, validate } = require('../middlewares');
const { ACCOUNT_ROLE } = require('../constants');
const controller = require('../controllers/rag.controller');
const validator = require('../validators/rag.validator');
const router = express.Router();
router.use(authenticate, authorize(ACCOUNT_ROLE.TECHNICIAN));
router.post('/queries', validate(validator.askQuestion), controller.askQuestion);
router.get('/conversations', validate(validator.listConversations), controller.listConversations);
router.get('/conversations/:conversationId', validate(validator.getConversation), controller.getConversation);
router.put('/queries/:queryId/feedback', validate(validator.saveFeedback), controller.saveFeedback);
module.exports = router;
