const httpStatus = require('./httpStatus');
const messages = require('./messages');
const NOTIFICATION_TYPE = require('./notificationType');
const {
    WATER_THRESHOLDS,
    THRESHOLD_FIELD_MAP,
    checkWaterThresholds,
} = require('./waterThresholds');

/**
 * Enums matching the database schema
 */
const ACCOUNT_ROLE = {
    ADMIN: 'ADMIN',
    FARM_OWNER: 'FARM_OWNER',
    TECHNICIAN: 'TECHNICIAN',
    EXPERT: 'EXPERT',
};

const ACCOUNT_STATUS = {
    PENDING_ACTIVATION: 'PENDING_ACTIVATION',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLOCKED: 'BLOCKED',
};

const VERIFICATION_PURPOSE = {
    ACCOUNT_ACTIVATION: 'ACCOUNT_ACTIVATION',
    PASSWORD_RESET: 'PASSWORD_RESET',
};

const SHRIMP_TYPE = {
    WHITELEG: 'WHITELEG',
    BLACK_TIGER: 'BLACK_TIGER',
};

const SEASON_STATUS = {
    PLANNING: 'PLANNING',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
};

const PERSONNEL_ROLE = {
    TECHNICIAN: 'TECHNICIAN',
    EXPERT: 'EXPERT',
};

const OPERATION_TYPE = {
    FEEDING: 'FEEDING',
    MINERAL: 'MINERAL',
    CHEMICAL: 'CHEMICAL',
    MEDICINE: 'MEDICINE',
    OTHER: 'OTHER',
};

const OPERATION_STATUS = {
    PLANNED: 'PLANNED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
};

const DOSE_BASIS = {
    FIXED_QUANTITY: 'FIXED_QUANTITY',
    PER_KG_BIOMASS: 'PER_KG_BIOMASS',
    PERCENT_BIOMASS: 'PERCENT_BIOMASS',
    PER_M3_WATER: 'PER_M3_WATER',
};

const SCHEDULE_CANCELLATION_TYPE = {
    PROTOCOL_SUPERSEDED: 'PROTOCOL_SUPERSEDED',
    TREATMENT_ABORTED: 'TREATMENT_ABORTED',
    SEASON_CANCELLED: 'SEASON_CANCELLED',
    MANUAL_CORRECTION: 'MANUAL_CORRECTION',
};

module.exports = {
    httpStatus,
    messages,
    ACCOUNT_ROLE,
    ACCOUNT_STATUS,
    VERIFICATION_PURPOSE,
    SHRIMP_TYPE,
    SEASON_STATUS,
    PERSONNEL_ROLE,
    OPERATION_TYPE,
    OPERATION_STATUS,
    DOSE_BASIS,
    SCHEDULE_CANCELLATION_TYPE,
    NOTIFICATION_TYPE,
    WATER_THRESHOLDS,
    THRESHOLD_FIELD_MAP,
    checkWaterThresholds,
};
